@startuml SellbotCogFactoryMethod

skinparam Monochrome reverse

title Factory Method pattern for creating Sellbot cogs

Cog *-- SellbotCog

package SellbotCogTypes {
  SellbotCog *-- ...
  SellbotCog *-- Telemarketer
  SellbotCog *-- ColdCaller
}

CogFactory -> SellbotCogTypes: creates

@enduml

