@startuml ComputerAbstractFactory

skinparam Monochrome reverse

title Abstract Factory pattern for creating parts for computers

class Component
{
  {abstract} getBrand()
  {abstract} getModel()
  {abstract} getPlatform()
}

class ComputerFactory
{
  + ComputerFactory()
  + createAndroid()
  + createLaptop()
}

' Android
class Android
{
  + getBrand()
  + getModel()
  + getPlatform()
  + getCPU()
}

class AndroidFactory
{
  + AndroidFactory()
  + createCPU()
}

' Laptop
class Laptop
{
  + getBrand()
  + getModel()
  + getPlatform()
  + getCPU()
}

class LaptopFactory
{
  + LaptopFactory()
  + createCPU()
}

' CPU
class CPU
{
  {abstract} getGeneration()
  {abstract} getNumberOfCores()
  {abstract} getMaxClockSpeedGHz()
}

class AndroidCPU
{
  + operator==()
  + getBrand()
  + getModel()
  + getPlatform()
  + getGeneration()
  + getNumberOfCores()
  + getMaxClockSpeedGHz()
}

class LaptopCPU
{
  + operator==()
  + getBrand()
  + getModel()
  + getPlatform()
  + getGeneration()
  + getNumberOfCores()
  + getMaxClockSpeedGHz()
}

class CPUFactory
{
}

Client -> ComputerFactory
ComputerFactory o-- AndroidFactory
ComputerFactory o-- LaptopFactory

Component <|-- Android
Component <|-- Laptop
Component <|-- CPU

AndroidFactory o-- Android
Android o-- AndroidCPU

LaptopFactory o-- Laptop
Laptop o-- LaptopCPU

AndroidFactory o-- CPUFactory
LaptopFactory o-- CPUFactory
CPUFactory o-- CPU
CPU <|-- AndroidCPU
CPU <|-- LaptopCPU

@enduml

